# Import locomotion and IGL

In [1]:
import sys
import os
PATH_TO_DIRECTORY = os.getcwd()
sys.path.append(PATH_TO_DIRECTORY)
import locomotion

from math import ceil, exp, log, sin, asin, pi, acosh, cosh, sinh, cos, acos, atanh, tanh
from numpy import min, mean, std, array, linalg, dot, cross
from scipy.optimize import minimize_scalar

In [2]:
import igl
import scipy as sp
import numpy as np
from meshplot import plot, subplot, interact

# Testing out IGL methods

In [44]:
# A cube, just trying out stuff
v = np.array([[-0.5, -0.5, 0.5],
              [0.5, -0.5, 0.5],
              [-0.5, 0.5 , 0.5],
              [0.5, 0.5, 0.5],
              [-0.5, 0.5, -0.5],
              [0.5, 0.5, -0.5],
              [-0.5, -0.5, -0.5],
              [0.5, -0.5, -0.5]])

f = np.array([[0, 1, 2],
              [1, 2, 3],
              [2, 3, 5],
              [2, 5, 4],
              [0, 2, 6],
              [0, 2, 4],
              [0, 1, 7],
              [0, 7, 6],
              [6, 7, 4],
              [7, 4, 5],
              [1, 3, 5],
              [1, 5, 7]])

In [45]:
v, f = igl.read_triangle_mesh("Med_NSS_07.delaunay.off")
# v: Array of vertices
# f: Array of vertices making up each face
v

array([[100.,  80.,  99.],
       [110.,  80.,  99.],
       [ 90.,  80.,  99.],
       ...,
       [190.,  70.,  50.],
       [190.,  80.,  50.],
       [190.,  90.,  50.]])

In [46]:
## Find the (longest ordered) open boundary - array indices of each vertex
bnd = igl.boundary_loop(f)

array([ 29,  40,  47,  36,  71,  97,  65,  83, 115, 179, 215, 282, 273,
       272, 271, 270, 269, 268, 267, 266, 265, 264, 274, 283, 290, 296,
       303, 308, 309, 311, 313, 315, 317, 318, 320, 321, 323, 325, 332,
       342, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 351, 341,
       230, 149, 147, 109,  78,  57,  35], dtype=int64)

In [69]:
## Map the boundary to a circle, preserving edge proportions
# Array of 2D coordinates, vertices of unit circle
bnd_uv = igl.map_vertices_to_circle(v, bnd)

In [70]:
p = plot(bnd_uv, f, uv=uv, shading={"wireframe": False, "flat": False}, return_plot=True)

@interact(mode=['3D','2D'])
def switch(mode):
    if mode == "3D":
        # Original faces and vertices
        plot(v, f, uv=uv, shading={"wireframe": False, "flat": False}, plot=p)
    if mode == "2D":
        # Parametrised vertices
        plot(bnd_uv, bnd_f, uv=uv, shading={"wireframe": True, "flat": False}, plot=p)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(1.7553567…

interactive(children=(Dropdown(description='mode', options=('3D', '2D'), value='3D'), Output()), _dom_classes=…

In [74]:
## Harmonic parametrization for the internal vertices
# All vertices mapped to unit circle given boundary circle

uv = igl.harmonic_weights(v, f, bnd, bnd_uv, 1)
# Make vertices 3D with 0 for plotting
v_p = np.hstack([uv, np.zeros((uv.shape[0],1))])

In [75]:
p = plot(v, f, uv=uv, shading={"wireframe": False, "flat": False}, return_plot=True)

@interact(mode=['3D','2D'])
def switch(mode):
    if mode == "3D":
        # Original faces and vertices
        plot(v, f, uv=uv, shading={"wireframe": False, "flat": False}, plot=p)
    if mode == "2D":
        # Parametrised vertices
        plot(v_p, f, uv=uv, shading={"wireframe": True, "flat": False}, plot=p)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(95.0, 45.…

interactive(children=(Dropdown(description='mode', options=('3D', '2D'), value='3D'), Output()), _dom_classes=…

# Get an animal as an example

In [3]:
info_file = PATH_TO_DIRECTORY + "/samples/sample_check.json"
animals = locomotion.getAnimalObjs( info_file )

LOG: Extracting coordinates for Animal SS_01...
LOG: Extracting coordinates for Animal SS_02...
LOG: Extracting coordinates for Animal NSS_01...
LOG: Extracting coordinates for Animal NSS_02...


In [4]:
# This is Animal SS_01
a = animals[0]

# Modifying getFlatCoordinates

In [13]:
PERTURBATION = 0.000000001
TOLERANCE = 0.00001
a.setPerturbation(PERTURBATION)
a.setTolerance(TOLERANCE)
a.setGridSize(10)

In [14]:
frequencies = locomotion.heatmap.getFrequencies(a, a.getExpStartTime(), a.getExpEndTime())
original_coordinates = locomotion.heatmap.getVertexCoordinates(a, frequencies)
a.setNumVerts(len(original_coordinates))
a.setRegularCoordinates(original_coordinates)
triangles = locomotion.heatmap.getTriangles(a)
a.setTriangulation(triangles)

#calculate and store colors for output file
colors = locomotion.heatmap.getColors(a)
a.setColors(colors)

v, f = original_coordinates, triangles

In [15]:
# insert IGL stuff here!!!
# Check that boundary vertices do the same thing
bnd = igl.boundary_loop(f)
# Check why the boundary from igl and from our own function is different?
# bnd = locomotion.heatmap.getBoundaryVertices(a)
# bnd

## Map the boundary to a circle, preserving edge proportions
# Array of 2D coordinates, vertices of unit circle
bnd_uv = igl.map_vertices_to_circle(v, bnd)

## Harmonic parametrization for the internal vertices
# All vertices mapped to unit circle given boundary circle

uv = igl.harmonic_weights(v, f, bnd, bnd_uv, 1)
uv

flat_coordinates = [[tanh(c[0])*cos(c[1]),tanh(c[0])*sin(c[1])] for c in uv]

TypeError: boundary_loop(): incompatible function arguments. The following argument types are supported:
    1. (f: array) -> object

Invoked with: [[0, 10, 11], [0, 11, 1], [1, 11, 12], [1, 12, 2], [2, 12, 13], [2, 13, 3], [3, 13, 14], [3, 14, 4], [4, 14, 15], [4, 15, 5], [5, 15, 16], [5, 16, 6], [6, 16, 17], [6, 17, 7], [7, 17, 18], [7, 18, 8], [8, 18, 19], [8, 19, 9], [10, 20, 21], [10, 21, 11], [11, 21, 22], [11, 22, 12], [12, 22, 23], [12, 23, 13], [13, 23, 24], [13, 24, 14], [14, 24, 25], [14, 25, 15], [15, 25, 26], [15, 26, 16], [16, 26, 27], [16, 27, 17], [17, 27, 28], [17, 28, 18], [18, 28, 29], [18, 29, 19], [20, 30, 31], [20, 31, 21], [21, 31, 32], [21, 32, 22], [22, 32, 33], [22, 33, 23], [23, 33, 34], [23, 34, 24], [24, 34, 35], [24, 35, 25], [25, 35, 36], [25, 36, 26], [26, 36, 37], [26, 37, 27], [27, 37, 38], [27, 38, 28], [28, 38, 39], [28, 39, 29], [30, 40, 41], [30, 41, 31], [31, 41, 42], [31, 42, 32], [32, 42, 43], [32, 43, 33], [33, 43, 44], [33, 44, 34], [34, 44, 45], [34, 45, 35], [35, 45, 46], [35, 46, 36], [36, 46, 47], [36, 47, 37], [37, 47, 48], [37, 48, 38], [38, 48, 49], [38, 49, 39], [40, 50, 51], [40, 51, 41], [41, 51, 52], [41, 52, 42], [42, 52, 53], [42, 53, 43], [43, 53, 54], [43, 54, 44], [44, 54, 55], [44, 55, 45], [45, 55, 56], [45, 56, 46], [46, 56, 57], [46, 57, 47], [47, 57, 58], [47, 58, 48], [48, 58, 59], [48, 59, 49], [50, 60, 61], [50, 61, 51], [51, 61, 62], [51, 62, 52], [52, 62, 63], [52, 63, 53], [53, 63, 64], [53, 64, 54], [54, 64, 65], [54, 65, 55], [55, 65, 66], [55, 66, 56], [56, 66, 67], [56, 67, 57], [57, 67, 68], [57, 68, 58], [58, 68, 69], [58, 69, 59], [60, 70, 71], [60, 71, 61], [61, 71, 72], [61, 72, 62], [62, 72, 73], [62, 73, 63], [63, 73, 74], [63, 74, 64], [64, 74, 75], [64, 75, 65], [65, 75, 76], [65, 76, 66], [66, 76, 77], [66, 77, 67], [67, 77, 78], [67, 78, 68], [68, 78, 79], [68, 79, 69], [70, 80, 81], [70, 81, 71], [71, 81, 82], [71, 82, 72], [72, 82, 83], [72, 83, 73], [73, 83, 84], [73, 84, 74], [74, 84, 85], [74, 85, 75], [75, 85, 86], [75, 86, 76], [76, 86, 87], [76, 87, 77], [77, 87, 88], [77, 88, 78], [78, 88, 89], [78, 89, 79], [80, 90, 91], [80, 91, 81], [81, 91, 92], [81, 92, 82], [82, 92, 93], [82, 93, 83], [83, 93, 94], [83, 94, 84], [84, 94, 95], [84, 95, 85], [85, 95, 96], [85, 96, 86], [86, 96, 97], [86, 97, 87], [87, 97, 98], [87, 98, 88], [88, 98, 99], [88, 99, 89], [90, 100, 101], [90, 101, 91], [91, 101, 102], [91, 102, 92], [92, 102, 103], [92, 103, 93], [93, 103, 104], [93, 104, 94], [94, 104, 105], [94, 105, 95], [95, 105, 106], [95, 106, 96], [96, 106, 107], [96, 107, 97], [97, 107, 108], [97, 108, 98], [98, 108, 109], [98, 109, 99], [100, 110, 111], [100, 111, 101], [101, 111, 112], [101, 112, 102], [102, 112, 113], [102, 113, 103], [103, 113, 114], [103, 114, 104], [104, 114, 115], [104, 115, 105], [105, 115, 116], [105, 116, 106], [106, 116, 117], [106, 117, 107], [107, 117, 118], [107, 118, 108], [108, 118, 119], [108, 119, 109], [110, 120, 121], [110, 121, 111], [111, 121, 122], [111, 122, 112], [112, 122, 123], [112, 123, 113], [113, 123, 124], [113, 124, 114], [114, 124, 125], [114, 125, 115], [115, 125, 126], [115, 126, 116], [116, 126, 127], [116, 127, 117], [117, 127, 128], [117, 128, 118], [118, 128, 129], [118, 129, 119], [120, 130, 131], [120, 131, 121], [121, 131, 132], [121, 132, 122], [122, 132, 133], [122, 133, 123], [123, 133, 134], [123, 134, 124], [124, 134, 135], [124, 135, 125], [125, 135, 136], [125, 136, 126], [126, 136, 137], [126, 137, 127], [127, 137, 138], [127, 138, 128], [128, 138, 139], [128, 139, 129], [130, 140, 141], [130, 141, 131], [131, 141, 142], [131, 142, 132], [132, 142, 143], [132, 143, 133], [133, 143, 144], [133, 144, 134], [134, 144, 145], [134, 145, 135], [135, 145, 146], [135, 146, 136], [136, 146, 147], [136, 147, 137], [137, 147, 148], [137, 148, 138], [138, 148, 149], [138, 149, 139], [140, 150, 151], [140, 151, 141], [141, 151, 152], [141, 152, 142], [142, 152, 153], [142, 153, 143], [143, 153, 154], [143, 154, 144], [144, 154, 155], [144, 155, 145], [145, 155, 156], [145, 156, 146], [146, 156, 157], [146, 157, 147], [147, 157, 158], [147, 158, 148], [148, 158, 159], [148, 159, 149], [150, 160, 161], [150, 161, 151], [151, 161, 162], [151, 162, 152], [152, 162, 163], [152, 163, 153], [153, 163, 164], [153, 164, 154], [154, 164, 165], [154, 165, 155], [155, 165, 166], [155, 166, 156], [156, 166, 167], [156, 167, 157], [157, 167, 168], [157, 168, 158], [158, 168, 169], [158, 169, 159], [160, 170, 171], [160, 171, 161], [161, 171, 172], [161, 172, 162], [162, 172, 173], [162, 173, 163], [163, 173, 174], [163, 174, 164], [164, 174, 175], [164, 175, 165], [165, 175, 176], [165, 176, 166], [166, 176, 177], [166, 177, 167], [167, 177, 178], [167, 178, 168], [168, 178, 179], [168, 179, 169], [170, 180, 181], [170, 181, 171], [171, 181, 182], [171, 182, 172], [172, 182, 183], [172, 183, 173], [173, 183, 184], [173, 184, 174], [174, 184, 185], [174, 185, 175], [175, 185, 186], [175, 186, 176], [176, 186, 187], [176, 187, 177], [177, 187, 188], [177, 188, 178], [178, 188, 189], [178, 189, 179], [180, 190, 191], [180, 191, 181], [181, 191, 192], [181, 192, 182], [182, 192, 193], [182, 193, 183], [183, 193, 194], [183, 194, 184], [184, 194, 195], [184, 195, 185], [185, 195, 196], [185, 196, 186], [186, 196, 197], [186, 197, 187], [187, 197, 198], [187, 198, 188], [188, 198, 199], [188, 199, 189]]

In [134]:
p = plot(v, f, uv=uv, shading={"wireframe": False, "flat": False}, return_plot=True)

@interact(mode=['3D','2D'])
def switch(mode):
    if mode == "3D":
        # Original faces and vertices
        plot(v, f, uv=uv, shading={"wireframe": False, "flat": False}, plot=p)
    if mode == "2D":
        # Parametrised vertices
        plot(v_p, f, uv=uv, shading={"wireframe": True, "flat": False}, plot=p)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(95.0, 45.…

interactive(children=(Dropdown(description='mode', options=('3D', '2D'), value='3D'), Output()), _dom_classes=…

In [155]:
f = a.getTriangulation()
# boundary_vertices = igl.boundary_loop(f)
type(a.getRegularCoordinates())
a.getRegularCoordinates()

[[0, 0, 43.17836348553121],
 [0, 10, 43.17836348553121],
 [0, 20, 43.17836348553121],
 [0, 30, 43.17836348553121],
 [0, 40, 43.17836348553121],
 [0, 50, 43.17836348553121],
 [0, 60, 43.17836348553121],
 [0, 70, 43.17836348553121],
 [0, 80, 43.17836348553121],
 [0, 90, 43.17836348553121],
 [10, 0, 43.17836348553121],
 [10, 10, 43.17836348553121],
 [10, 20, 43.17836348553121],
 [10, 30, 43.17836348553121],
 [10, 40, 43.17836348553121],
 [10, 50, 43.17836348553121],
 [10, 60, 43.17836348553121],
 [10, 70, 43.17836348553121],
 [10, 80, 43.17836348553121],
 [10, 90, 43.17836348553121],
 [20, 0, 43.17836348553121],
 [20, 10, 43.17836348553121],
 [20, 20, 43.17836348553121],
 [20, 30, 43.17836348553121],
 [20, 40, 43.17836348553121],
 [20, 50, 43.17836348553121],
 [20, 60, 43.17836348553121],
 [20, 70, 43.17836348553121],
 [20, 80, 43.17836348553121],
 [20, 90, 43.17836348553121],
 [30, 0, 43.17836348553121],
 [30, 10, 43.17836348553121],
 [30, 20, 43.17836348553121],
 [30, 30, 43.17836348553

In [17]:
grid_size = 10
# locomotion.trajectory.getCurveData( a )
# locomotion.heatmap.getSurfaceData(a, grid_size)
flat = locomotion.heatmap.getFlatCoordinates(a)

[[  0.           0.          43.17836349]
 [  0.          10.          43.17836349]
 [  0.          20.          43.17836349]
 [  0.          30.          43.17836349]
 [  0.          40.          43.17836349]
 [  0.          50.          43.17836349]
 [  0.          60.          43.17836349]
 [  0.          70.          43.17836349]
 [  0.          80.          43.17836349]
 [  0.          90.          43.17836349]
 [ 10.           0.          43.17836349]
 [ 10.          10.          43.17836349]
 [ 10.          20.          43.17836349]
 [ 10.          30.          43.17836349]
 [ 10.          40.          43.17836349]
 [ 10.          50.          43.17836349]
 [ 10.          60.          43.17836349]
 [ 10.          70.          43.17836349]
 [ 10.          80.          43.17836349]
 [ 10.          90.          43.17836349]
 [ 20.           0.          43.17836349]
 [ 20.          10.          43.17836349]
 [ 20.          20.          43.17836349]
 [ 20.          30.          43.17

In [19]:
flat

[[-0.43411564284552123, 0.006390858047571407, 0],
 [-0.42965115608994237, 0.05244618607913534, 0],
 [-0.4169552155194943, 0.09638912341686368, 0],
 [-0.3967034835017728, 0.13630691545409263, 0],
 [-0.36993414714968925, 0.17053471235121184, 0],
 [-0.3379518385611276, 0.1977412210832073, 0],
 [-0.3022125295639516, 0.21698150610383055, 0],
 [-0.26420255089875916, 0.2277156857455989, 0],
 [-0.22532393070568899, 0.22979695905437114, 0],
 [-0.18679585663806797, 0.2234357836562123, 0],
 [-0.4301005308804927, -0.03972827410576936, 0],
 [-0.4160329151862911, 0.012663915358168276, 0],
 [-0.39655245143287965, 0.060582396203986935, 0],
 [-0.3715354774847028, 0.10313434491219779, 0],
 [-0.34142071422451387, 0.13945639390174286, 0],
 [-0.3069460186782772, 0.16868215534922473, 0],
 [-0.26918458774448134, 0.19014897977640974, 0],
 [-0.2294432837629942, 0.20362435714001093, 0],
 [-0.18911674456460673, 0.20949742435295338, 0],
 [-0.14957902495887346, 0.20914873543619467, 0],
 [-0.41781033423375236, -0.0